import { spawnSync as nodeSpawnSync, type SpawnSyncReturns } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { LocalWorkspace } from "./localWorkspace.js";
import { RuntimeCapability } from "./runtimeCapabilities.js";
import type {
  RuntimeAdapter,
  RuntimeAgentRequest,
  RuntimeAgentResult,
  RuntimeAutonomy,
  RuntimeBinding,
  RuntimeGuardReport,
  RuntimeGuards,
  RuntimeProbe,
  RuntimeUsage,
  RuntimeWorkspace,
  RuntimeWorkRoot,
  SpawnSync,
} from "./runtimeAdapter.js";

/**
 * Pulls `developer_instructions` out of one of this framework's own
 * `.codex/agents/<role>.toml` bindings (OFF02 S6 schema, written by our
 * generator — see OFF03/P7). Hand-parsed on purpose: the file is generated by
 * us from a template we own, the same dependency-free reasoning the hooks and
 * their TS mirrors use. Supports the two shapes the generator emits — a TOML
 * multiline basic string (`"""…"""`) and a single-line basic string.
 *
 * Returns null when the key is absent or empty, so a malformed binding fails
 * loudly at the caller instead of sending an empty role definition to exec.
 */
export function extractDeveloperInstructions(toml: string): string | null {
  const multiline = toml.match(/developer_instructions\s*=\s*"""([\s\S]*?)"""/);
  if (multiline) {
    const value = multiline[1].replace(/\r\n/g, "\n").replace(/\\"""/g, '"""').trim();
    return value.length > 0 ? value : null;
  }
  const single = toml.match(/developer_instructions\s*=\s*"((?:[^"\\\n]|\\.)*)"\s*(?:#.*)?$/m);
  if (single) {
    const value = single[1].replace(/\\"/g, '"').replace(/\\n/g, "\n").trim();
    return value.length > 0 ? value : null;
  }
  return null;
}

/**
 * Tolerant reader over the documented `codex exec --json` JSONL event stream
 * (OFF02 S5 documents the event-type names; payload shapes beyond them are not
 * pinned down). Scans every parsed event and keeps the LAST numeric usage
 * fields / model string it actually finds — anything absent stays undefined,
 * per the absent ≠ 0 invariant. Never throws on a line it cannot parse.
 */
export function parseCodexJsonl(stdout: string): { usage: RuntimeUsage; model?: string } {
  let inputTokens: number | undefined;
  let outputTokens: number | undefined;
  let cachedInputTokens: number | undefined;
  let costUsd: number | undefined;
  let model: string | undefined;
  for (const line of stdout.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("{")) continue;
    let event: Record<string, unknown>;
    try {
      event = JSON.parse(trimmed) as Record<string, unknown>;
    } catch {
      continue;
    }
    const usage = event.usage as Record<string, unknown> | undefined;
    if (usage && typeof usage === "object") {
      if (typeof usage.input_tokens === "number") inputTokens = usage.input_tokens;
      if (typeof usage.output_tokens === "number") outputTokens = usage.output_tokens;
      if (typeof usage.cache_read_input_tokens === "number") cachedInputTokens = usage.cache_read_input_tokens;
    }
    if (typeof event.total_cost_usd === "number") costUsd = event.total_cost_usd;
    if (typeof event.model === "string" && event.model.length > 0) model = event.model;
  }
  return {
    usage:
      inputTokens !== undefined || outputTokens !== undefined || cachedInputTokens !== undefined || costUsd !== undefined
        ? { inputTokens, outputTokens, cachedInputTokens, costUsd }
        : {},
    model,
  };
}

/**
 * The `RuntimeAdapter` for Codex — the second target `runtimeAdapter.ts` was
 * designed against, written to prove the interface is not Claude-Code-shaped
 * in disguise.
 *
 * **THIS IS A PARTIAL, ASSUMPTION-HEAVY IMPLEMENTATION — READ BEFORE TRUSTING IT.**
 *
 * Nobody has run this adapter against a real `codex` install in this repo. Every
 * flag, exit-code convention, and capability claim below is either (a) publicly
 * documented Codex CLI behaviour as of this framework's knowledge cutoff, marked
 * with a confidence note, or (b) an explicit assumption mirroring
 * `claudeCodeAdapter.ts`'s shape where Codex's actual behaviour is unknown.
 * This is deliberately marked partial with stated assumptions rather than made
 * to look complete. Capability detection is what turns "assumed" into
 * "verified" once this runs against a real installation — until then, treat
 * every `capabilities` claim here as a hypothesis, not a fact.
 *
 * WHAT IS REASONABLY CONFIDENT
 * - `codex exec "<prompt>"` runs one non-interactive turn and exits — the shape
 *   `executeAgent` needs (a single request in, a single result out).
 * - `--sandbox <read-only|workspace-write|danger-full-access>` and
 *   `--ask-for-approval <untrusted|on-failure|on-request|never>` are Codex's own
 *   permission axes — the closest thing it has to Claude Code's
 *   `--permission-mode`.
 * - `AGENTS.md` (and a project `.codex/config.toml`) are Codex's project-level,
 *   committed configuration — the `PROJECT_LEVEL_BINDING` capability is claimed
 *   on that basis alone, not on any guard mechanism.
 *
 * WHAT IS NOT CLAIMED, AND WHY
 * - `NAMED_AGENTS` — Codex's *interactive* clients officially load custom agents
 *   from `.codex/agents/*.toml` (name/description/developer_instructions), and
 *   that `.toml` shape is exactly what this framework commits. What official
 *   docs do NOT document is an `exec`-level flag that
 *   selects a named agent for a headless run. Until one is documented, the role
 *   definition is still read here and folded into the prompt via documented
 *   flags only — which is why the capability stays unclaimed. Do not flip this
 *   to `true` without a confirmed native `exec` selector.
 * - `PRE_TOOL_GUARD` / `POST_TOOL_GUARD` / `EXIT_GUARD` / `PER_AGENT_EXIT_GUARD`
 *   — no confirmed, generally-available hook mechanism equivalent to Claude
 *   Code's `PreToolUse`/`Stop`/`SubagentStop` array in `settings.json`. Some
 *   Codex builds are reported to run arbitrary notify commands, but the shape
 *   and reliability (including whether it fires at all under `codex exec`,
 *   which is what this framework spawns) is not something this task can verify
 *   without a real install. Claiming these would let a guard-dependent stage
 *   believe it is enforced when it silently is not — the exact fail-open failure
 *   `policies/security.md` §5d warns about. `binding.guardConfigPath` is `null`
 *   for the same reason (see its doc-comment in `runtimeAdapter.ts`: `null` is
 *   the honest answer that forces guards to be covered post-hoc).
 * - `STRUCTURED_RESULT` / `COST_REPORTING` — the adapter speaks two
 *   documented machine surfaces: `--json` (JSONL event stream) and `-o/--output-
 *   last-message` (final message written to a file). Token/model values are
 *   taken from event payloads **only where actually present** — payload shapes
 *   beyond the documented event-type names are not pinned down, so anything not
 *   found stays undefined rather than guessed (never a fabricated 0). That
 *   best-effort posture is still short of a claimable structured envelope.
 * - `INTERACTIVE_PROMPTS` — `codex exec` is explicitly non-interactive; a stage
 *   that needs to put a question to a person (`business-analyst`) cannot run
 *   through this adapter as designed. This is the same reasoning
 *   `runtimeCapabilities.ts`'s header already anticipated for `codex exec`.
 * - `models` — no default catalogue is declared. Guessing exact model ids here
 *   would be wild guessing; a caller that knows its installation's reachable
 *   models passes them via `CodexAdapterOptions.models`. Left empty,
 *   `RuntimeRegistry.reaching()` correctly reports that this runtime reaches
 *   nothing, rather than a fabricated answer that reaches everything.
 * - `PARALLEL_EXECUTION` — same as `claudeCodeAdapter.ts`: unclaimed by any
 *   adapter yet.
 */

const CODEX_CAPABILITIES: readonly RuntimeCapability[] = [
  RuntimeCapability.MODEL_SELECTION,
  RuntimeCapability.PROJECT_LEVEL_BINDING,
];

/** `RuntimeAutonomy` onto Codex's own sandbox/approval axes — assumption, unverified against a real install. See file header. */
const SANDBOX_MODE: Record<RuntimeAutonomy, string> = {
  "read-only": "read-only",
  propose: "workspace-write",
  edit: "workspace-write",
  full: "danger-full-access",
};

const APPROVAL_MODE: Record<RuntimeAutonomy, string> = {
  "read-only": "on-request",
  propose: "on-request",
  edit: "on-failure",
  full: "never",
};

export interface CodexAdapterOptions {
  /** Root of the target project — where `.codex/agents/<role>.md` and `_docs/` live. */
  projectRoot: string;
  /** Injectable for tests; defaults to `child_process.spawnSync`. */
  spawnSync?: SpawnSync;
  /** Default per-run timeout in ms, overridable per request via `RuntimeAgentRequest.timeoutMs`. */
  timeoutMs?: number;
  /**
   * Models this installation is known to reach. No default — see file header.
   * `RuntimeRegistry.reaching()` answers nothing for this runtime until a caller
   * states what its own Codex installation/config can actually reach.
   */
  models?: readonly string[];
  /**
   * OFF10 M6 — when set, every run passes `--output-schema` (the schema written
   * to a temp file) and the `-o` final-message file is parsed as JSON onto
   * `RuntimeAgentResult.structured`. **Off by default** for the same reason as
   * the Claude adapter: structured replies are a caller decision, never a side
   * effect of this adapter existing.
   */
  outputSchema?: Record<string, unknown>;
}

export class CodexAdapter implements RuntimeAdapter {
  readonly id = "codex";
  readonly displayName = "Codex";
  readonly binding: RuntimeBinding = {
    // `.codex/agents/*.toml` is the officially documented custom-agent location
    // and schema: required `name`, `description`, `developer_instructions`.
    // The adapter reads exactly that file and folds its developer_instructions
    // into the prompt — still necessary because no exec-level named-agent
    // selector is documented (see header).
    dir: ".codex",
    definitionPath: (role) => `.codex/agents/${role}.toml`,
    // No confirmed project-level guard-wiring file for Codex. `null` is the
    // deliberate, honest answer `runtimeAdapter.ts` documents for exactly this
    // situation — these guards must be covered post-hoc, not assumed.
    guardConfigPath: null,
  };
  readonly capabilities: ReadonlySet<RuntimeCapability> = new Set(CODEX_CAPABILITIES);
  readonly models: ReadonlySet<string>;
  readonly workspace: RuntimeWorkspace;

  private readonly spawn: SpawnSync;
  private readonly defaultTimeoutMs: number;
  private readonly outputSchema?: Record<string, unknown>;

  constructor(opts: CodexAdapterOptions) {
    this.workspace = new LocalWorkspace({ root: opts.projectRoot });
    this.spawn = opts.spawnSync ?? (nodeSpawnSync as unknown as SpawnSync);
    this.defaultTimeoutMs = opts.timeoutMs ?? 30 * 60_000;
    this.models = new Set(opts.models ?? []);
    this.outputSchema = opts.outputSchema;
  }

  async probe(): Promise<RuntimeProbe> {
    let proc: SpawnSyncReturns<string>;
    try {
      proc = this.spawn("codex", ["--version"], { encoding: "utf8", timeout: 10_000, maxBuffer: 1024 * 1024 });
    } catch (e) {
      return { available: false, reason: String(e) };
    }
    if (proc.error) return { available: false, reason: proc.error.message };
    if (proc.status !== 0) return { available: false, reason: `\`codex --version\` exited ${proc.status ?? "unknown"}` };
    return { available: true, version: (proc.stdout ?? "").trim() };
  }

  async executeAgent(req: RuntimeAgentRequest): Promise<RuntimeAgentResult> {
    // No guard mechanism is claimed (see file header), so any requested guard
    // axis is reported unenforced up front — never silently dropped.
    const guards = noGuardMechanismReport(req.guards);

    // NAMED_AGENTS is not claimed (no documented exec-level selector): the
    // role's official `.toml` binding is read and its developer_instructions
    // folded into the prompt on every run.
    let roleDefinition: string | null;
    try {
      roleDefinition = await this.workspace.readFile(req.definitionPath);
    } catch (e) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [`could not read role binding ${req.definitionPath}: ${String(e)}`],
      };
    }
    if (roleDefinition === null) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [
          `no role binding found at ${req.definitionPath} — no exec-level named-agent flag is documented, ` +
            `so this adapter needs that file to fold into the prompt (see codexAdapter.ts header)`,
        ],
      };
    }
    const instructions = extractDeveloperInstructions(roleDefinition);
    if (instructions === null) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [
          `role binding ${req.definitionPath} has no developer_instructions — this binding does not match ` +
            `the generated schema (name/description/developer_instructions); regenerate it via sta init`,
        ],
      };
    }

    const prompt = `${instructions}\n\n---\n\n${req.prompt}`;

    // Preflight write roots become sandbox-native --add-dir grants
    // (OS-enforced) instead of living only in env the sandbox never read.
    const addDirs = addDirArgsFor(req.workRoots, req.autonomy);

    // Two documented machine surfaces, used together:
    //   --json                    → stdout becomes a JSONL event stream (usage/model scanned tolerantly)
    //   -o/--output-last-message  → the final message lands in a file, independent of stream shape
    // The scratch files live in the OS temp dir: the orchestrator's own write, like
    // installation.yaml — never inside any guarded workspace root.
    const lastMessageFile = path.join(os.tmpdir(), `sta-codex-last-${process.pid}-${Date.now()}.txt`);
    let schemaFile: string | null = null;
    if (this.outputSchema) {
      schemaFile = path.join(os.tmpdir(), `sta-codex-schema-${process.pid}-${Date.now()}.json`);
      fs.writeFileSync(schemaFile, JSON.stringify(this.outputSchema), "utf8");
    }
    const args = [
      "exec",
      "--sandbox",
      SANDBOX_MODE[req.autonomy],
      "--ask-for-approval",
      APPROVAL_MODE[req.autonomy],
      ...addDirs,
      "--json",
      ...(schemaFile ? ["--output-schema", schemaFile] : []),
      "-o",
      lastMessageFile,
      prompt,
    ];

    let proc: SpawnSyncReturns<string>;
    try {
      proc = this.spawn("codex", args, {
        cwd: req.cwd,
        encoding: "utf8",
        timeout: req.timeoutMs ?? this.defaultTimeoutMs,
        maxBuffer: 64 * 1024 * 1024,
        // Same channel as `claudeCodeAdapter.ts` — set unconditionally since it
        // costs nothing if the runtime never asks a guard to read it.
        env: { ...process.env, ...req.env, AGENTCLAUDE_ROLE: req.role },
      });
    } catch (e) {
      return { status: "UNAVAILABLE", exitCode: null, text: "", usage: {}, guards, diagnostics: [`failed to spawn \`codex\`: ${String(e)}`] };
    }

    if (proc.error) {
      const code = (proc.error as NodeJS.ErrnoException).code;
      if (code === "ENOENT") {
        return { status: "UNAVAILABLE", exitCode: null, text: "", usage: {}, guards, diagnostics: [`\`codex\` binary not found: ${proc.error.message}`] };
      }
      if (code === "ETIMEDOUT") {
        return { status: "TIMEOUT", exitCode: proc.status ?? null, text: "", usage: {}, guards, diagnostics: [`\`codex exec\` timed out: ${proc.error.message}`] };
      }
      return { status: "ERROR", exitCode: proc.status ?? null, text: "", usage: {}, guards, diagnostics: [`\`codex\` errored: ${proc.error.message}`] };
    }

    const stdout = proc.stdout ?? "";
    const stderr = proc.stderr ?? "";
    const failed = proc.status !== 0;

    // Final message: the `-o` file when Codex wrote one; otherwise fall back to
    // the previous behaviour (stdout/stderr as text) so a run against an older
    // or non-conforming CLI still returns something truthful. On schema runs the
    // same file holds the structured document — parsed when it parses, absent
    // (with a diagnostic) when it doesn't.
    let text: string;
    let structured: unknown;
    let structuredParseFailed = false;
    let lastMessageFileMissing = false;
    try {
      const fromFile = fs.readFileSync(lastMessageFile, "utf8");
      text = fromFile.length > 0 ? fromFile : stdout;
      if (schemaFile && fromFile.length > 0) {
        try {
          structured = JSON.parse(fromFile);
        } catch {
          structuredParseFailed = true;
        }
      }
    } catch {
      text = failed ? stderr || stdout : stdout;
      lastMessageFileMissing = true;
    } finally {
      try {
        fs.rmSync(lastMessageFile, { force: true });
      } catch {
        // best-effort cleanup of our own temp files
      }
      if (schemaFile) {
        try {
          fs.rmSync(schemaFile, { force: true });
        } catch {
          // best-effort cleanup of our own temp files
        }
      }
    }

    // Usage/model: whatever the JSONL events actually carried, nothing invented.
    const { usage, model } = parseCodexJsonl(stdout);

    const diagnostics: string[] = [];
    if (lastMessageFileMissing) {
      diagnostics.push("no -o/--output-last-message file was written; final message fell back to raw CLI output");
    }
    if (structuredParseFailed) {
      diagnostics.push("--output-schema was requested but the final message did not parse as JSON — structured is absent for this run");
    }
    const readCaveat = unreadableWorkRootCaveat(req.workRoots, req.autonomy);
    if (readCaveat) diagnostics.push(readCaveat);

    return {
      status: failed ? "ERROR" : "OK",
      exitCode: proc.status ?? null,
      text,
      usage,
      // Only claimed when an event actually carried it — never guessed.
      model,
      guards,
      diagnostics,
      structured,
      raw: { stdout, stderr },
    };
  }
}

/** Every requested guard axis is unenforced, because no guard mechanism is claimed at all (`binding.guardConfigPath` is `null`). */
function noGuardMechanismReport(requested: RuntimeGuards): RuntimeGuardReport {
  const wantsPreToolGuard = requested.writeAllow.length > 0 || requested.writeDeny.length > 0 || requested.forbidCommands.length > 0;
  const wantsExitGuard = requested.exitChecks.length > 0;
  if (!wantsPreToolGuard && !wantsExitGuard) return { enforced: [], unenforced: [] };
  const unenforced = [
    ...(wantsPreToolGuard ? [RuntimeCapability.PRE_TOOL_GUARD] : []),
    ...(wantsExitGuard ? [RuntimeCapability.EXIT_GUARD, RuntimeCapability.PER_AGENT_EXIT_GUARD] : []),
  ];
  return {
    enforced: [],
    unenforced,
    reason: "codexAdapter.ts claims no guard mechanism (binding.guardConfigPath is null) — see file header for why",
  };
}

/**
 * OFF10 M5 — the preflight write roots, carried natively instead of by
 * convention. Until now a Target repo this run may write reached Codex only as
 * an env var the sandbox never read; `--add-dir` hands the same directories to
 * the OS-enforced sandbox itself, which is strictly stronger than anything the
 * env+hooks channel can promise.
 *
 * Mapping rules (deliberately least-privilege):
 * - write roots under `propose`/`edit` (the two workspace-write autonomies) →
 *   one `--add-dir <path>` each.
 * - `read-only` autonomy runs in a read-only sandbox where adds are meaningless.
 * - `full` maps to danger-full-access — everything is writable anyway, and
 *   passing roots there would imply they were the boundary when they are not.
 * - read-only work roots are NOT added: `--add-dir` grants write access, and
 *   per-directory read grants are not exposed by any documented exec flag. The
 *   caller sees a diagnostic whenever that gap is live (see `executeAgent`),
 *   so reliance on Codex's default read posture is stated, never silent.
 */
export function addDirArgsFor(
  workRoots: readonly RuntimeWorkRoot[] | undefined,
  autonomy: RuntimeAutonomy,
): string[] {
  if (!workRoots || workRoots.length === 0) return [];
  if (autonomy !== "propose" && autonomy !== "edit") return [];
  const args: string[] = [];
  for (const root of workRoots) {
    if (root.access === "write") args.push("--add-dir", root.path);
  }
  return args;
}

/** Read-only roots that could not be granted natively — surfaced, not swallowed. */
export function unreadableWorkRootCaveat(workRoots: readonly RuntimeWorkRoot[] | undefined, autonomy: RuntimeAutonomy): string | null {
  if (!workRoots || (autonomy !== "propose" && autonomy !== "edit")) return null;
  const readOnly = workRoots.filter((r) => r.access === "read");
  if (readOnly.length === 0) return null;
  return (
    `${readOnly.length} read-only work root(s) (${readOnly.map((r) => r.targetId).join(", ")}) rely on Codex's ` +
    `default read posture — codex exec exposes no documented per-directory read grant today`
  );
}
