import { spawnSync as nodeSpawnSync, type SpawnSyncReturns } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { LocalWorkspace } from "./localWorkspace.js";
import { RuntimeCapability } from "./runtimeCapabilities.js";
import { resolveNpmCliScript as resolveNpmCliScriptImpl, type CommandResolver } from "./npmCliResolver.js";
import { SingleShotLifecycle } from "./singleShotLifecycle.js";
import type {
  ExecutorAttemptRef,
  ExecutorCancelOutcome,
  ExecutorEvidence,
  ExecutorPort,
  PreparedExecutorAttempt,
} from "./executorPort.js";
import type {
  RuntimeAdapter,
  RuntimeAgentRequest,
  RuntimeAgentResult,
  RuntimeAutonomy,
  RuntimeBinding,
  RuntimeGuardReport,
  RuntimeGuards,
  RuntimeProbe,
  RuntimeUsage,
  RuntimeWorkspace,
  SpawnSync,
} from "./runtimeAdapter.js";

/**
 * Pulls `developer_instructions` out of one of this framework's own
 * `.codex/agents/<role>.toml` bindings (OFF02 S6 schema, written by our
 * generator — see OFF03/P7). Hand-parsed on purpose: the file is generated by
 * us from a template we own, the same dependency-free reasoning the hooks and
 * their TS mirrors use. Supports the two shapes the generator emits — a TOML
 * multiline basic string (`"""…"""`) and a single-line basic string.
 *
 * Returns null when the key is absent or empty, so a malformed binding fails
 * loudly at the caller instead of sending an empty role definition to exec.
 */
export function extractDeveloperInstructions(toml: string): string | null {
  const multiline = toml.match(/developer_instructions\s*=\s*"""([\s\S]*?)"""/);
  if (multiline) {
    const value = multiline[1].replace(/\r\n/g, "\n").replace(/\\"""/g, '"""').trim();
    return value.length > 0 ? value : null;
  }
  const single = toml.match(/developer_instructions\s*=\s*"((?:[^"\\\n]|\\.)*)"\s*(?:#.*)?$/m);
  if (single) {
    const value = single[1].replace(/\\"/g, '"').replace(/\\n/g, "\n").trim();
    return value.length > 0 ? value : null;
  }
  return null;
}

/**
 * Tolerant reader over the documented `codex exec --json` JSONL event stream
 * (OFF02 S5 documents the event-type names; payload shapes beyond them are not
 * pinned down). Scans every parsed event and keeps the LAST numeric usage
 * fields / model string it actually finds — anything absent stays undefined,
 * per the absent ≠ 0 invariant. Never throws on a line it cannot parse.
 */
export function parseCodexJsonl(stdout: string): { usage: RuntimeUsage; model?: string } {
  let inputTokens: number | undefined;
  let outputTokens: number | undefined;
  let cachedInputTokens: number | undefined;
  let costUsd: number | undefined;
  let model: string | undefined;
  for (const line of stdout.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("{")) continue;
    let event: Record<string, unknown>;
    try {
      event = JSON.parse(trimmed) as Record<string, unknown>;
    } catch {
      continue;
    }
    const usage = event.usage as Record<string, unknown> | undefined;
    if (usage && typeof usage === "object") {
      if (typeof usage.input_tokens === "number") inputTokens = usage.input_tokens;
      if (typeof usage.output_tokens === "number") outputTokens = usage.output_tokens;
      // Current Codex JSONL uses `cached_input_tokens`; keep the older
      // `cache_read_input_tokens` spelling as a compatibility fallback.
      if (typeof usage.cached_input_tokens === "number") cachedInputTokens = usage.cached_input_tokens;
      else if (typeof usage.cache_read_input_tokens === "number") cachedInputTokens = usage.cache_read_input_tokens;
      // T-V8-012: no cache-*creation* counter has ever been observed in a Codex
      // JSONL event; `RuntimeUsage.cacheCreationInputTokens` stays unset here,
      // same absent-≠-0 posture as every other unconfirmed field on this adapter.
    }
    if (typeof event.total_cost_usd === "number") costUsd = event.total_cost_usd;
    if (typeof event.model === "string" && event.model.length > 0) model = event.model;
  }
  return {
    usage:
      inputTokens !== undefined || outputTokens !== undefined || cachedInputTokens !== undefined || costUsd !== undefined
        ? { inputTokens, outputTokens, cachedInputTokens, costUsd }
        : {},
    model,
  };
}

/**
 * The `RuntimeAdapter` for Codex — the second target `runtimeAdapter.ts` was
 * designed against, written to prove the interface is not Claude-Code-shaped
 * in disguise.
 *
 * **HEADLESS WRITES USE A PER-RUN NATIVE POLICY — INTERACTIVE CODEX DOES NOT.**
 *
 * V12 UAT exercised the invocation surfaces against real Codex CLI 0.154.0 and
 * 0.155.1 installs. The adapter now compiles every guarded headless run into a
 * custom native permission profile: broad read access, packet-scoped writes,
 * protected framework metadata, no network, an isolated execpolicy, and OS
 * deny rules for resolved forbidden executables such as Git. This is
 * intentionally the same host-native
 * security posture as the Claude adapter, not a container boundary.
 *
 * WHAT IS REASONABLY CONFIDENT
 * - `codex exec "<prompt>"` runs one non-interactive turn and exits — the shape
 *   `executeAgent` needs (a single request in, a single result out).
 * - Guarded writes use a custom permission profile rather than the legacy
 *   `--sandbox` modes. `codex exec` is non-interactive, so the adapter passes
 *   `approval_policy="never"` through `--config`.
 * - `AGENTS.md` (and a project `.codex/config.toml`) are Codex's project-level,
 *   committed configuration — the `PROJECT_LEVEL_BINDING` capability is claimed
 *   on that basis alone, not on any guard mechanism.
 *
 * WHAT IS NOT CLAIMED, AND WHY
 * - `NAMED_AGENTS` — Codex's *interactive* clients officially load custom agents
 *   from `.codex/agents/*.toml` (name/description/developer_instructions), and
 *   that `.toml` shape is exactly what this framework commits. What official
 *   docs do NOT document is an `exec`-level flag that
 *   selects a named agent for a headless run. Until one is documented, the role
 *   definition is still read here and folded into the prompt via documented
 *   flags only — which is why the capability stays unclaimed. Do not flip this
 *   to `true` without a confirmed native `exec` selector.
 * - `POST_TOOL_GUARD` / `EXIT_GUARD` / `PER_AGENT_EXIT_GUARD` — V12 UAT proved
 *   project hooks need a trust bypass, a crashing hook fails open, and Stop did
 *   not fire under `codex exec`. The adapter does not trust those hooks. It
 *   claims `PRE_TOOL_GUARD` only for the native permission/execpolicy boundary
 *   assembled by this adapter for the exact run; provider-neutral exit checks
 *   remain the runner's responsibility.
 * - `STRUCTURED_RESULT` — real-install UAT pinned the JSONL + output-schema
 *   round trip, so the normalised structured result is now a declared
 *   capability. `COST_REPORTING` remains unclaimed: no cost value is present.
 *   The adapter speaks two
 *   documented machine surfaces: `--json` (JSONL event stream) and `-o/--output-
 *   last-message` (final message written to a file). Token/model values are
 *   taken from event payloads **only where actually present** — payload shapes
 *   beyond the documented event-type names are not pinned down, so anything not
 *   found stays undefined rather than guessed (never a fabricated 0). That
 *   best-effort posture is still short of a claimable structured envelope.
 * - `INTERACTIVE_PROMPTS` — `codex exec` is explicitly non-interactive; a stage
 *   that needs to put a question to a person (`business-analyst`) cannot run
 *   through this adapter as designed. This is the same reasoning
 *   `runtimeCapabilities.ts`'s header already anticipated for `codex exec`.
 * - `models` — no default catalogue is declared. Guessing exact model ids here
 *   would be wild guessing; a caller that knows its installation's reachable
 *   models passes them via `CodexAdapterOptions.models`. Left empty,
 *   `RuntimeRegistry.reaching()` correctly reports that this runtime reaches
 *   nothing, rather than a fabricated answer that reaches everything.
 * - `PARALLEL_EXECUTION` — same as `claudeCodeAdapter.ts`: unclaimed by any
 *   adapter yet.
 */

const CODEX_CAPABILITIES: readonly RuntimeCapability[] = [
  RuntimeCapability.MODEL_SELECTION,
  RuntimeCapability.PRE_TOOL_GUARD,
  RuntimeCapability.PROJECT_LEVEL_BINDING,
  RuntimeCapability.STRUCTURED_RESULT,
  // V13 TASK-014 — the lifecycle implemented through `SingleShotLifecycle`:
  // fresh-session resume from the persisted attempt journal, honest cancel
  // accounting, and evidence computed from the spawn and the work-root
  // snapshots around it. No session reference is lifted: no session id has
  // been verified in the `codex exec --json` stream, and one is never invented.
  RuntimeCapability.ATTEMPT_RESUME,
  RuntimeCapability.ATTEMPT_CANCEL,
  RuntimeCapability.EVIDENCE_COLLECTION,
];

export const CODEX_PERMISSION_PROFILE_UNAVAILABLE = "CODEX_PERMISSION_PROFILE_UNAVAILABLE";

/**
 * Codex's own final `ERROR:` lines when the provider refused to serve, each
 * captured verbatim from a real `codex exec` run against a stub upstream
 * (`planning/v6/v6-2-evidence.md`), never taken from vendor documentation:
 *
 *   ERROR: exceeded retry limit, last status: 429 Too Many Requests
 *   ERROR: unexpected status 401 Unauthorized: Incorrect API key provided., url: …
 *   ERROR: unexpected status 403 Forbidden: You do not have access to this model., url: …
 *
 * Line-anchored because every codex run — successful ones included — emits
 * unrelated `ERROR: Reconnecting…` and MCP `AuthRequired` noise on the same
 * stream; an unanchored substring match would classify healthy runs as
 * provider refusals. A 5xx is deliberately absent: it surfaces as
 * `ERROR: We're currently experiencing high demand…`, which is not a refusal to
 * serve this account and stays ERROR.
 */
const PROVIDER_REFUSAL_PATTERN = /^ERROR: (?:exceeded retry limit, last status: 429\b|unexpected status 40[13]\b)/m;

/** Read-only runs retain the stable legacy mode; writable runs use the richer permission profile below. */
const SANDBOX_MODE: Record<RuntimeAutonomy, string> = {
  "read-only": "read-only",
  propose: "workspace-write",
  edit: "workspace-write",
  full: "danger-full-access",
};

const CODEX_PERMISSION_PROFILE = "sta_run";
const ALWAYS_READ_ONLY_IN_WORKSPACE = [".git", ".codex", ".agents"] as const;

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function normalizeGuardPattern(pattern: string): string {
  const normalized = pattern.trim().replace(/\\/g, "/").replace(/^\.\//, "").replace(/\/+$/, "");
  if (
    normalized.length === 0 ||
    normalized.startsWith("/") ||
    /^[A-Za-z]:\//.test(normalized) ||
    normalized.split("/").some((part) => part === "..")
  ) {
    throw new Error(`unsafe guard path pattern ${JSON.stringify(pattern)} — paths must be non-empty and workspace-relative`);
  }
  return normalized;
}

function segmentMatcher(segment: string): RegExp {
  const escaped = segment.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, "[^/]*");
  return new RegExp(`^${escaped}$`);
}

/**
 * Codex supports exact read/write paths and a trailing `/**`, but not interior
 * read/write globs. Expand only wildcard directory segments that already
 * exist, retaining later literal segments so a role may create its owned file.
 */
export function codexPermissionPathsFor(root: string, rawPattern: string): string[] {
  const pattern = normalizeGuardPattern(rawPattern);
  if (pattern === "**") return ["."];
  const trailingTree = pattern.endsWith("/**");
  const withoutTree = trailingTree ? pattern.slice(0, -3).replace(/\/$/, "") : pattern;
  if (!withoutTree.includes("*")) return [withoutTree || "."];

  const parts = withoutTree.split("/");
  const walk = (relative: string, index: number): string[] => {
    if (index >= parts.length) return [relative || "."];
    const segment = parts[index]!;
    if (!segment.includes("*")) {
      const next = relative ? `${relative}/${segment}` : segment;
      return walk(next, index + 1);
    }
    const absoluteParent = path.join(root, ...relative.split("/").filter(Boolean));
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(absoluteParent, { withFileTypes: true });
    } catch {
      return [];
    }
    const matcher = segmentMatcher(segment);
    const needsDirectory = index < parts.length - 1 || trailingTree;
    return entries.flatMap((entry) => {
      if (!matcher.test(entry.name) || (needsDirectory && !entry.isDirectory())) return [];
      const next = relative ? `${relative}/${entry.name}` : entry.name;
      return walk(next, index + 1);
    });
  };
  return [...new Set(walk("", 0))];
}

export interface CodexPermissionInvocation {
  readonly args: readonly string[];
  readonly guards: RuntimeGuardReport;
}

/** Compile packet command denials into Codex's strictest execpolicy decision. */
export function codexExecPolicyFor(
  commands: readonly string[],
  platform: NodeJS.Platform = process.platform,
): string {
  const basenames = commands.map((rawCommand) => {
    const command = rawCommand.trim();
    if (!/^[A-Za-z0-9._-]+$/.test(command)) {
      throw new Error(`unsupported forbidden command ${JSON.stringify(rawCommand)} — expected one executable basename`);
    }
    return command;
  });
  const policyNames = basenames.flatMap((command) =>
    platform === "win32" && path.extname(command).length === 0
      ? [command, ...[".exe", ".cmd", ".bat", ".com", ".ps1"].map((extension) => `${command}${extension}`)]
      : [command],
  );
  return [...new Set(policyNames)]
    .map((command) =>
      `prefix_rule(pattern = [${JSON.stringify(command)}], decision = "forbidden", justification = "Blocked by the software-team-agents run contract")`,
    )
    .join("\n");
}

interface PreparedCodexHome {
  readonly path: string;
  cleanup(): void;
}

/** Adapter-owned companion to the execpolicy parser for opaque shell strings. */
const CODEX_GIT_GUARD_SCRIPT = String.raw`'use strict';
let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { raw += chunk; });
process.stdin.on('end', () => {
  let input;
  try { input = JSON.parse(raw); }
  catch { console.error('Blocked: malformed PreToolUse input.'); process.exit(2); }
  const command = String(input?.tool_input?.command || '');
  const gitExecutable = /(?:^|[\s;&|()])(?:["']?(?:[A-Za-z]:[\\/][^"';|]*[\\/]|\/[^"';|]*\/)?)git(?:\.exe|\.cmd|\.bat|\.com|\.ps1)?(?=$|[\s"';&|()])/i;
  const dotGit = /(?:^|[\\/])\.git(?:[\\/]|$)/i;
  if (gitExecutable.test(command) || dotGit.test(command)) {
    console.error('Blocked: Git commands and direct .git access belong to the human operator.');
    process.exit(2);
  }
  process.exit(0);
});
`;

function codexInlineGitHookArgs(runHome: string): string[] {
  const script = path.join(runHome, "git-guard.cjs");
  const command = `node ${JSON.stringify(script)}`;
  const handler = `{ type = "command", command = ${tomlString(command)}, command_windows = ${tomlString(command)}, timeout = 10 }`;
  const registration = `{ matcher = "Bash|PowerShell", hooks = [${handler}] }`;
  return ["--config", `hooks.PreToolUse=[${registration}]`];
}

function prepareCodexRunHome(
  commands: readonly string[],
  projectRoot: string,
  sourceHome: string,
  inheritAuth: boolean,
): PreparedCodexHome {
  const runHome = fs.mkdtempSync(path.join(os.tmpdir(), "sta-codex-home-"));
  try {
    const policy = codexExecPolicyFor(commands);
    if (policy.length > 0) {
      const rulesDir = path.join(runHome, "rules");
      fs.mkdirSync(rulesDir, { recursive: true });
      fs.writeFileSync(path.join(rulesDir, "sta.rules"), `${policy}\n`, "utf8");
    }

    // Project-local config, hooks, and execpolicy are ignored for this run.
    // Only the adapter's permission profile and execpolicy are active.
    fs.writeFileSync(
      path.join(runHome, "config.toml"),
      `[projects.${tomlString(path.resolve(projectRoot))}]\ntrust_level = "untrusted"\n`,
      "utf8",
    );
    fs.writeFileSync(path.join(runHome, "git-guard.cjs"), CODEX_GIT_GUARD_SCRIPT, "utf8");

    if (inheritAuth) {
      const authSource = path.join(sourceHome, "auth.json");
      if (fs.existsSync(authSource)) {
        const authTarget = path.join(runHome, "auth.json");
        // Copy, never link: a provider token refresh inside the temporary home
        // must not be able to mutate the user's persistent credential file.
        fs.copyFileSync(authSource, authTarget);
        try {
          fs.chmodSync(authTarget, 0o600);
        } catch {
          // Windows ACLs, not POSIX mode bits, are the effective protection.
        }
      }
    }

    return {
      path: runHome,
      cleanup: () => {
        try {
          fs.rmSync(runHome, { recursive: true, force: true });
        } catch {
          // best-effort cleanup of an orchestrator-owned temporary directory
        }
      },
    };
  } catch (error) {
    try {
      fs.rmSync(runHome, { recursive: true, force: true });
    } catch {
      // preserve the original preparation failure
    }
    throw error;
  }
}

/**
 * Build one self-contained native permission profile. `:root = read` matches
 * Claude Code's read posture; only packet-authorized workspace paths are
 * writable. Deny globs become read-only paths because the contract denies
 * mutation, not inspection.
 */
export function codexPermissionInvocationFor(
  req: Pick<RuntimeAgentRequest, "cwd" | "autonomy" | "guards" | "workRoots" | "env">,
  platform: NodeJS.Platform = process.platform,
): CodexPermissionInvocation {
  const wantsPreTool = requiresPreToolGuard(req.guards, req.autonomy);
  const wantsExit = req.guards.exitChecks.length > 0;
  if (!wantsPreTool) {
    return {
      args: ["--sandbox", SANDBOX_MODE[req.autonomy], "--config", 'approval_policy="never"'],
      guards: guardReport(false, wantsExit),
    };
  }

  const cwd = path.resolve(req.cwd);
  const cwdWorkRoot = req.workRoots?.find((root) => path.resolve(root.path) === cwd);
  if (cwdWorkRoot?.access === "read") {
    throw new Error(`cwd ${cwd} is Target "${cwdWorkRoot.targetId}" bound read-only; refusing to turn it into a writable Codex workspace root`);
  }

  const permissions = new Map<string, "read" | "write">();
  permissions.set(".", "read");
  for (const pattern of req.guards.writeAllow) {
    const expanded = codexPermissionPathsFor(cwd, pattern);
    if (expanded.length === 0) {
      throw new Error(`write-allow pattern ${JSON.stringify(pattern)} cannot be represented safely for Codex because its wildcard parent does not exist`);
    }
    for (const allowed of expanded) permissions.set(allowed, "write");
  }
  for (const protectedPath of ALWAYS_READ_ONLY_IN_WORKSPACE) permissions.set(protectedPath, "read");
  for (const pattern of req.guards.writeDeny) {
    for (const denied of codexPermissionPathsFor(cwd, pattern)) permissions.set(denied, "read");
  }

  const workspaceEntries = [...permissions.entries()]
    .map(([permissionPath, access]) => `${tomlString(permissionPath)} = ${tomlString(access)}`)
    .join(", ");
  const filesystemEntries = [
    '":root" = "read"',
    `":workspace_roots" = { ${workspaceEntries} }`,
  ].filter(Boolean).join(", ");
  const profile = `{ filesystem = { ${filesystemEntries} }, network = { enabled = false } }`;
  const writeRoots = [...new Set((req.workRoots ?? [])
    .filter((root) => root.access === "write")
    .map((root) => path.resolve(root.path))
    .filter((root) => root !== cwd))];
  const args = [
    "--strict-config",
    "--ephemeral",
    "-C",
    cwd,
    "--config",
    "project_root_markers=[]",
    "--config",
    'approval_policy="never"',
    ...(platform === "win32" ? ["--config", 'windows.sandbox="elevated"'] : []),
    "--config",
    `default_permissions=${tomlString(CODEX_PERMISSION_PROFILE)}`,
    "--config",
    `permissions.${CODEX_PERMISSION_PROFILE}=${profile}`,
    ...writeRoots.flatMap((root) => ["--add-dir", root]),
  ];
  return { args, guards: guardReport(true, wantsExit) };
}

/** Codex's current configurable reasoning levels for the GPT-5.6/Astra family. */
const CODEX_REASONING_EFFORTS = new Set(["low", "medium", "high", "xhigh", "max"]);

export interface CodexAdapterOptions {
  /** Root of the target project — where `.codex/agents/<role>.md` and `_docs/` live. */
  projectRoot: string;
  /** Injectable for tests; defaults to `child_process.spawnSync`. */
  spawnSync?: SpawnSync;
  /** Default per-run timeout in ms, overridable per request via `RuntimeAgentRequest.timeoutMs`. */
  timeoutMs?: number;
  /**
   * Injectable for tests; defaults to `resolveNpmCliScript`. Only consulted when
   * `platform` is win32 and a spawn came back ENOENT — the one case where the
   * bare command name is known-unusable rather than merely absent (an
   * npm-installed `codex` is a `.cmd`/`.ps1` shim spawnSync cannot execute).
   */
  resolveCommand?: CommandResolver;
  /** Injectable for tests; defaults to `process.platform`. */
  platform?: string;
  /**
   * Models this installation is known to reach. No default — see file header.
   * `RuntimeRegistry.reaching()` answers nothing for this runtime until a caller
   * states what its own Codex installation/config can actually reach.
   */
  models?: readonly string[];
  /**
   * OFF10 M6 — when set, every run passes `--output-schema` (the schema written
   * to a temp file) and the `-o` final-message file is parsed as JSON onto
   * `RuntimeAgentResult.structured`. **Off by default** for the same reason as
   * the Claude adapter: structured replies are a caller decision, never a side
   * effect of this adapter existing.
   */
  outputSchema?: Record<string, unknown>;
  /** Injectable for tests; roots the lifecycle's attempt journal instead of the OS temp dir default. */
  journalRoot?: string;
}

export class CodexAdapter implements ExecutorPort {
  readonly id = "codex";
  readonly displayName = "Codex";
  readonly binding: RuntimeBinding = {
    // `.codex/agents/*.toml` is the officially documented custom-agent location
    // and schema: required `name`, `description`, `developer_instructions`.
    // The adapter reads exactly that file and folds its developer_instructions
    // into the prompt — still necessary because no exec-level named-agent
    // selector is documented (see header).
    dir: ".codex",
    definitionPath: (role) => `.codex/agents/${role}.toml`,
    // Project hooks remain intentionally untrusted. `null` says the binding
    // file itself proves no guard; guarded headless runs are certified by the
    // per-run permission profile and isolated execpolicy below.
    guardConfigPath: null,
    // Headless execution does not trust project hooks. It compiles the active
    // packet into a native permission profile and reports that exact run.
    guardEnforcement: "per-run",
  };
  readonly capabilities: ReadonlySet<RuntimeCapability> = new Set(CODEX_CAPABILITIES);
  readonly models: ReadonlySet<string>;
  readonly workspace: RuntimeWorkspace;

  private readonly spawn: SpawnSync;
  private readonly defaultTimeoutMs: number;
  private readonly outputSchema?: Record<string, unknown>;
  private readonly inheritCodexAuth: boolean;
  private readonly resolveCommand: CommandResolver;
  private readonly platform: string;
  /** V13 TASK-014 — the lifecycle port, over this adapter's one spawn-and-parse implementation. */
  private readonly lifecycle: SingleShotLifecycle;

  constructor(opts: CodexAdapterOptions) {
    this.workspace = new LocalWorkspace({ root: opts.projectRoot });
    this.spawn = opts.spawnSync ?? (nodeSpawnSync as unknown as SpawnSync);
    this.defaultTimeoutMs = opts.timeoutMs ?? 30 * 60_000;
    this.models = new Set(opts.models ?? []);
    this.outputSchema = opts.outputSchema;
    this.resolveCommand = opts.resolveCommand ?? resolveNpmCliScriptImpl;
    this.platform = opts.platform ?? process.platform;
    // Unit tests inject a fake process and must never reach into the user's
    // credential store. Production construction inherits only auth.json into
    // the isolated per-run home; config, plugins, MCPs, and user rules do not.
    this.inheritCodexAuth = opts.spawnSync === undefined;
    // No `sessionRefFrom`: no session id has been verified in the `codex exec
    // --json` event stream, so evidence records none rather than inventing one.
    this.lifecycle = new SingleShotLifecycle(this.id, { run: (req) => this.executeAgent(req), journalRoot: opts.journalRoot });
  }

  // V13 TASK-014 — the lifecycle port, delegating to the shared single-shot
  // implementation over `executeAgent`.
  prepare(req: RuntimeAgentRequest): Promise<PreparedExecutorAttempt> {
    return this.lifecycle.prepare(req);
  }
  execute(attempt: PreparedExecutorAttempt): Promise<RuntimeAgentResult> {
    return this.lifecycle.execute(attempt);
  }
  resume(ref: ExecutorAttemptRef): Promise<RuntimeAgentResult> {
    return this.lifecycle.resume(ref);
  }
  cancel(ref: ExecutorAttemptRef): Promise<ExecutorCancelOutcome> {
    return this.lifecycle.cancel(ref);
  }
  collectResult(ref: ExecutorAttemptRef): Promise<RuntimeAgentResult | null> {
    return this.lifecycle.collectResult(ref);
  }
  collectEvidence(ref: ExecutorAttemptRef): Promise<ExecutorEvidence> {
    return this.lifecycle.collectEvidence(ref);
  }

  /**
   * One spawn, plus the single retry it is allowed: on Windows an ENOENT from a
   * bare command name usually means "npm shim", not "not installed" — resolve
   * the shim's real entry script and try once more (same seam as
   * `claudeCodeAdapter.ts`). Any other error (or a resolver that finds nothing)
   * returns the first result untouched.
   */
  private spawnResolved(
    command: string,
    args: string[],
    options: Parameters<SpawnSync>[2],
  ): { proc: SpawnSyncReturns<string>; resolvedThrough: string | null } {
    const proc = this.spawn(command, args, options);
    const code = proc.error ? (proc.error as NodeJS.ErrnoException).code : undefined;
    if (code !== "ENOENT" || this.platform !== "win32") return { proc, resolvedThrough: null };
    const resolved = this.resolveCommand(command);
    if (!resolved) return { proc, resolvedThrough: null };
    return { proc: this.spawn(resolved.file, [...resolved.prefixArgs, ...args], options), resolvedThrough: resolved.file };
  }

  async probe(): Promise<RuntimeProbe> {
    let proc: SpawnSyncReturns<string>;
    try {
      ({ proc } = this.spawnResolved("codex", ["--version"], { encoding: "utf8", timeout: 10_000, maxBuffer: 1024 * 1024 }));
    } catch (e) {
      return { available: false, reason: String(e) };
    }
    if (proc.error) return { available: false, reason: proc.error.message };
    if (proc.status !== 0) return { available: false, reason: `\`codex --version\` exited ${proc.status ?? "unknown"}` };
    return { available: true, version: (proc.stdout ?? "").trim() };
  }

  async executeAgent(req: RuntimeAgentRequest): Promise<RuntimeAgentResult> {
    let invocation: CodexPermissionInvocation;
    try {
      invocation = codexPermissionInvocationFor(req);
    } catch (error) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards: guardReport(false, req.guards.exitChecks.length > 0, requiresPreToolGuard(req.guards, req.autonomy)),
        diagnostics: [
          `${CODEX_PERMISSION_PROFILE_UNAVAILABLE}: refusing guarded codex exec before spawn — ${String(error)}`,
        ],
      };
    }
    const guards = invocation.guards;

    // NAMED_AGENTS is not claimed (no documented exec-level selector): the
    // role's official `.toml` binding is read and its developer_instructions
    // folded into the prompt on every run.
    let roleDefinition: string | null;
    try {
      roleDefinition = await this.workspace.readFile(req.definitionPath);
    } catch (e) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [`could not read role binding ${req.definitionPath}: ${String(e)}`],
      };
    }
    if (roleDefinition === null) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [
          `no role binding found at ${req.definitionPath} — no exec-level named-agent flag is documented, ` +
            `so this adapter needs that file to fold into the prompt (see codexAdapter.ts header)`,
        ],
      };
    }
    const instructions = extractDeveloperInstructions(roleDefinition);
    if (instructions === null) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [
          `role binding ${req.definitionPath} has no developer_instructions — this binding does not match ` +
            `the generated schema (name/description/developer_instructions); regenerate it via sta init`,
        ],
      };
    }

    const prompt = `${instructions}\n\n---\n\n${req.prompt}`;

    // Tier bindings are explicit runtime choices.  Unlike role frontmatter,
    // they must become Codex CLI arguments or the run merely records the
    // intended tier while silently using Codex's configured default.
    if (req.modelExplicit && req.model && this.models.size > 0 && !this.models.has(req.model)) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [
          `refusing to run: model "${req.model}" is not in this workspace's configured Codex tier catalogue ` +
            `(${[...this.models].join(", ")})`,
        ],
      };
    }
    if (req.effort && !CODEX_REASONING_EFFORTS.has(req.effort)) {
      return {
        status: "ERROR",
        exitCode: null,
        text: "",
        usage: {},
        guards,
        diagnostics: [
          `refusing to run: reasoning effort "${req.effort}" is not supported by the Codex tier adapter ` +
            `(${[...CODEX_REASONING_EFFORTS].join(", ")})`,
        ],
      };
    }

    let runHome: PreparedCodexHome | null = null;
    if (requiresPreToolGuard(req.guards, req.autonomy)) {
      try {
        const sourceHome = req.env?.CODEX_HOME ?? process.env.CODEX_HOME ?? path.join(os.homedir(), ".codex");
        runHome = prepareCodexRunHome(req.guards.forbidCommands, req.cwd, sourceHome, this.inheritCodexAuth);
      } catch (error) {
        return {
          status: "ERROR",
          exitCode: null,
          text: "",
          usage: {},
          guards: guardReport(false, req.guards.exitChecks.length > 0, true),
          diagnostics: [
            `${CODEX_PERMISSION_PROFILE_UNAVAILABLE}: refusing guarded codex exec before spawn — ${String(error)}`,
          ],
        };
      }
    }

    // Two documented machine surfaces, used together:
    //   --json                    → stdout becomes a JSONL event stream (usage/model scanned tolerantly)
    //   -o/--output-last-message  → the final message lands in a file, independent of stream shape
    // The scratch files live in the OS temp dir: the orchestrator's own write, like
    // installation.yaml — never inside any guarded workspace root.
    const lastMessageFile = path.join(os.tmpdir(), `sta-codex-last-${process.pid}-${Date.now()}.txt`);
    let schemaFile: string | null = null;
    if (this.outputSchema) {
      schemaFile = path.join(os.tmpdir(), `sta-codex-schema-${process.pid}-${Date.now()}.json`);
      fs.writeFileSync(schemaFile, JSON.stringify(this.outputSchema), "utf8");
    }
    const args = [
      "exec",
      ...invocation.args,
      ...(runHome ? codexInlineGitHookArgs(runHome.path) : []),
      ...(req.modelExplicit && req.model ? ["--model", req.model] : []),
      ...(req.effort ? ["--config", `model_reasoning_effort=\"${req.effort}\"`] : []),
      "--json",
      ...(schemaFile ? ["--output-schema", schemaFile] : []),
      "-o",
      lastMessageFile,
      prompt,
    ];

    let proc: SpawnSyncReturns<string>;
    let resolvedThrough: string | null = null;
    try {
      ({ proc, resolvedThrough } = this.spawnResolved("codex", args, {
        cwd: req.cwd,
        encoding: "utf8",
        timeout: req.timeoutMs ?? this.defaultTimeoutMs,
        maxBuffer: 64 * 1024 * 1024,
        // Same channel as `claudeCodeAdapter.ts` — set unconditionally since it
        // costs nothing if the runtime never asks a guard to read it.
        env: {
          ...process.env,
          ...req.env,
          STA_ROLE: req.role,
          ...(runHome ? { CODEX_HOME: runHome.path } : {}),
        },
      }));
    } catch (e) {
      return { status: "UNAVAILABLE", exitCode: null, text: "", usage: {}, guards, diagnostics: [`failed to spawn \`codex\`: ${String(e)}`] };
    } finally {
      runHome?.cleanup();
    }

    if (proc.error) {
      const code = (proc.error as NodeJS.ErrnoException).code;
      if (code === "ENOENT") {
        const diagnostics = [`\`codex\` binary not found: ${proc.error.message}`];
        if (resolvedThrough === null && this.platform === "win32") {
          diagnostics.push(
            "on Windows an npm-installed `codex` is a .cmd/.ps1 shim spawnSync cannot execute; no resolvable entry was found — install the native build or expose a real executable on PATH",
          );
        }
        return { status: "UNAVAILABLE", exitCode: null, text: "", usage: {}, guards, diagnostics };
      }
      if (code === "ETIMEDOUT") {
        return { status: "TIMEOUT", exitCode: proc.status ?? null, text: "", usage: {}, guards, diagnostics: [`\`codex exec\` timed out: ${proc.error.message}`] };
      }
      return { status: "ERROR", exitCode: proc.status ?? null, text: "", usage: {}, guards, diagnostics: [`\`codex\` errored: ${proc.error.message}`] };
    }

    const stdout = proc.stdout ?? "";
    const stderr = proc.stderr ?? "";
    const failed = proc.status !== 0;

    // Final message: the `-o` file when Codex wrote one; otherwise fall back to
    // the previous behaviour (stdout/stderr as text) so a run against an older
    // or non-conforming CLI still returns something truthful. On schema runs the
    // same file holds the structured document — parsed when it parses, absent
    // (with a diagnostic) when it doesn't.
    let text: string;
    let structured: unknown;
    let structuredParseFailed = false;
    let lastMessageFileMissing = false;
    try {
      const fromFile = fs.readFileSync(lastMessageFile, "utf8");
      text = fromFile.length > 0 ? fromFile : stdout;
      if (schemaFile && fromFile.length > 0) {
        try {
          structured = JSON.parse(fromFile);
        } catch {
          structuredParseFailed = true;
        }
      }
    } catch {
      text = failed ? stderr || stdout : stdout;
      lastMessageFileMissing = true;
    } finally {
      try {
        fs.rmSync(lastMessageFile, { force: true });
      } catch {
        // best-effort cleanup of our own temp files
      }
      if (schemaFile) {
        try {
          fs.rmSync(schemaFile, { force: true });
        } catch {
          // best-effort cleanup of our own temp files
        }
      }
    }

    // Usage/model: whatever the JSONL events actually carried, nothing invented.
    const { usage, model } = parseCodexJsonl(stdout);

    const diagnostics: string[] = [];
    if (lastMessageFileMissing) {
      diagnostics.push("no -o/--output-last-message file was written; final message fell back to raw CLI output");
    }
    if (structuredParseFailed) {
      diagnostics.push("--output-schema was requested but the final message did not parse as JSON — structured is absent for this run");
    }
    // See PROVIDER_REFUSAL_PATTERN: a refusal to serve must not spend the
    // task's retry budget or trigger recovery for something the task did not
    // cause.
    if (failed && PROVIDER_REFUSAL_PATTERN.test(stderr)) {
      const line = stderr.split("\n").find((l) => PROVIDER_REFUSAL_PATTERN.test(l)) ?? "";
      return {
        status: "UNAVAILABLE",
        exitCode: proc.status ?? null,
        text: "",
        usage,
        model,
        guards,
        diagnostics: [...diagnostics, `\`codex\` provider refused to serve: ${line.trim()}`],
        raw: { stdout, stderr },
      };
    }

    return {
      status: failed ? "ERROR" : "OK",
      exitCode: proc.status ?? null,
      text,
      usage,
      // Only claimed when an event actually carried it — never guessed.
      model,
      guards,
      diagnostics,
      structured,
      raw: { stdout, stderr },
    };
  }
}

/** Per-run truth: native permissions cover pre-tool writes/commands; exit checks remain provider-neutral. */
function guardReport(preToolEnforced: boolean, wantsExitGuard: boolean, wantsPreToolGuard = preToolEnforced): RuntimeGuardReport {
  if (!wantsPreToolGuard && !wantsExitGuard) return { enforced: [], unenforced: [] };
  const enforced = preToolEnforced ? [RuntimeCapability.PRE_TOOL_GUARD] : [];
  const unenforced = [
    ...(!preToolEnforced && wantsPreToolGuard ? [RuntimeCapability.PRE_TOOL_GUARD] : []),
    ...(wantsExitGuard ? [RuntimeCapability.EXIT_GUARD, RuntimeCapability.PER_AGENT_EXIT_GUARD] : []),
  ];
  return {
    enforced,
    unenforced,
    reason: wantsExitGuard
      ? "Codex write/command scope is enforced by the per-run native permission profile and isolated execpolicy; exit checks are enforced by the provider-neutral runner"
      : undefined,
  };
}

/** A read-only OS sandbox makes write/command denial non-operative; every writable mode needs a real pre-tool guard. */
function requiresPreToolGuard(requested: RuntimeGuards, autonomy: RuntimeAutonomy): boolean {
  return autonomy !== "read-only" &&
    (requested.writeAllow.length > 0 || requested.writeDeny.length > 0 || requested.forbidCommands.length > 0);
}
